name: login-auth
recipe: laravel
config:
  php: '8.3'
  composer_version: '2.8.0'
  via: apache:2.4
  webroot: .
  database: mariadb:11.3
  cache: none
  xdebug: true
  services:
    appserver:
      build_as_root:
      - cd ./authentication-be && composer install
      - mv .env.base .env
      - php artisan key:generate
      - php artisan migrate
      - php artisan vendor:publish --provider="PHPOpenSourceSaver\JWTAuth\Providers\LaravelServiceProvider"
      - php artisan jwt:secret | awk '{print "JWT_SECRET="$0}' >> output_file
    database:
      portforward: true
    phpmyadmin:
      type: phpmyadmin
